AWSTemplateFormatVersion: 2010-09-09
Description: | 
Kittens Carousel is a static website application deployed on AWS Simple Storage Service (S3), 
served through Cloudfront and Route 53 using AWS Cloudformation Service.
Parameters:

  MyVPC:
    Description: VPC Id of your existing account
    Type: AWS::EC2::VPC::Id

  KeyName:
    Description: Please enter your Key pair
    Type: AWS::EC2::KeyPair::KeyName

  Subnets:
    Description: Please select your subnets used by ALB
    Type: List<AWS::EC2::Subnet::Id>
  

Resources:
  
Outputs: